name: "workflows"

on: [push, pull_request]

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup-node
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: setup-yarn
        run: yarn install
      - name: lint
        run: npm run lint
      - name: type-check
        run: npm run ts:check
      - name: test
        run: npm run test
      - name: Test coverage
        uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: "yarn"
          test-script: npm run test:coverage
